

    let DestinationData = [
        {
          id: 1,
          img: require("../assets/images/popular/slide-1.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$220.0/Night",
          person: 2,
        },
        {
          id: 2,
          img: require("../assets/images/popular/slide-2.webp"),
          title: "Queen’s Room",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$320.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 3,
          img: require("../assets/images/popular/slide-3.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$420.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 4,
          img: require("../assets/images/popular/slide-1.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$520.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 5,
          img: require("../assets/images/popular/slide-2.webp"),
          title: "Queen’s Room",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$620.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 6,
          img: require("../assets/images/popular/slide-3.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$720.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 7,
          img: require("../assets/images/popular/slide-1.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$820.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 8,
          img: require("../assets/images/popular/slide-2.webp"),
          title: "Queen’s Room",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$920.0/Night",
          checkIn: "",
          checkOut: "",
        },
        {
          id: 9,
          img: require("../assets/images/popular/slide-3.webp"),
          title: "Family Suit",
          bed: "2 Beds",
          feet: "150 Sq.feet",
          desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
          price: "$1020.0/Night",
          checkIn: "",
          checkOut: "",
        },
      ];


export default DestinationData;